# Generated by Django 5.1.6 on 2025-02-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='avatar.png', null=True, upload_to='profile/'),
        ),
    ]
