# Generated by Django 5.1.6 on 2025-02-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0002_users_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='images/avatar.png', null=True, upload_to='profile/'),
        ),
    ]
