# Generated by Django 5.0.3 on 2025-02-24 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0005_users_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapprovers',
            name='checker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_checker', to=settings.AUTH_USER_MODEL),
        ),
    ]
