# Generated by Django 5.0.3 on 2025-02-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0006_userapprovers_checker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='josettings',
            name='userrole',
            field=models.CharField(choices=[('Requestor', 'Requestor'), ('Approver', 'Approver'), ('Maintenance', 'Maintenance'), ('QA Checker', 'QA Checker'), ('Facilitator', 'Facilitator')], default='Requestor', max_length=20),
        ),
    ]
