# Generated by Django 5.0.3 on 2025-03-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0007_alter_josettings_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='job_order_user',
            field=models.BooleanField(default=False),
        ),
    ]
