# Generated by Django 5.0.3 on 2025-03-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0008_users_job_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='manhours_user',
            field=models.BooleanField(default=False),
        ),
    ]
