# Generated by Django 5.0.3 on 2025-03-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0009_users_manhours_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='manhours_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
