# Generated by Django 5.0.3 on 2025-03-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0010_users_manhours_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='manhours_staff',
            field=models.BooleanField(default=False),
        ),
    ]
