# Generated by Django 5.0.3 on 2025-03-12 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0011_users_manhours_staff'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.line')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_designation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
