# Generated by Django 5.0.3 on 2025-03-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0012_userline'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='monitoring_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='monitoring_sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='monitoring_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='monitoring_user',
            field=models.BooleanField(default=False),
        ),
    ]
