# Generated by Django 5.0.3 on 2025-03-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0013_users_monitoring_manager_users_monitoring_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='monitoring_qad',
            field=models.BooleanField(default=False),
        ),
    ]
