# Generated by Django 5.0.3 on 2025-03-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0014_users_monitoring_qad'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='monitoring_staff',
            field=models.BooleanField(default=False),
        ),
    ]
