# Generated by Django 5.0.3 on 2025-03-29 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0016_alter_users_line'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='line',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_line', to='settings.line'),
        ),
    ]
