# Generated by Django 5.0.3 on 2025-04-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0017_alter_users_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='is_approver',
            new_name='job_order_approver',
        ),
        migrations.AddField(
            model_name='users',
            name='job_order_checker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='job_order_facilitator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='job_order_maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
