# Generated by Django 5.0.3 on 2025-04-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0018_rename_is_approver_users_job_order_approver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='job_order_requestor',
            field=models.BooleanField(default=False),
        ),
    ]
