# Generated by Django 5.0.3 on 2025-04-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0019_users_job_order_requestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapprovers',
            name='module',
            field=models.CharField(choices=[('Job Order', 'Job Order'), ('Manhours', 'Manhours'), ('Monitoring', 'Monitoring')], max_length=200, null=True),
        ),
    ]
