# Generated by Django 5.0.3 on 2025-04-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0020_alter_userapprovers_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapprovers',
            name='approver_role',
            field=models.CharField(choices=[('Checker', 'Checker'), ('Supervisor', 'Supervisor')], max_length=100, null=True),
        ),
    ]
