# Generated by Django 5.0.3 on 2025-04-21 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0021_userapprovers_approver_role'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_line', to='settings.line'),
        ),
    ]
