# Generated by Django 5.0.3 on 2025-04-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0022_alter_users_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapprovers',
            name='approver_role',
            field=models.CharField(choices=[('Requestor', 'Requestor'), ('Checker', 'Checker'), ('Supervisor', 'Supervisor')], max_length=100, null=True),
        ),
    ]
