# Generated by Django 5.0.3 on 2025-04-21 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0023_alter_userapprovers_approver_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapprovers',
            name='checker',
        ),
    ]
