# Generated by Django 5.0.3 on 2025-04-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0024_remove_userapprovers_checker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapprovers',
            name='approver_role',
            field=models.CharField(choices=[('Requestor', 'Requestor'), ('Checker', 'Checker'), ('Approver', 'Approver')], max_length=100, null=True),
        ),
    ]
