# Generated by Django 5.0.3 on 2025-05-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0025_alter_userapprovers_approver_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='images/profile/avatar.png', null=True, upload_to='profile/'),
        ),
    ]
