# Generated by Django 5.0.3 on 2025-05-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0026_alter_users_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='position',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Clerk', 'Clerk'), ('Assistant', 'Assistant'), ('Innovator', 'Innovator'), ('Supervisor', 'Supervisor'), ('Manager', 'Manager')], max_length=100, null=True),
        ),
    ]
