# Generated by Django 5.0.3 on 2025-05-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0027_users_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='dcf_approver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='dcf_requestor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='dcf_user',
            field=models.BooleanField(default=False),
        ),
    ]
