# Generated by Django 5.0.3 on 2025-05-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0028_users_dcf_approver_users_dcf_requestor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ecis_facilitator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='ecis_requestor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='ecis_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='overtime_allocator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='overtime_checker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='overtime_requestor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='overtime_user',
            field=models.BooleanField(default=False),
        ),
    ]
