# Generated by Django 5.0.3 on 2025-05-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0029_users_ecis_facilitator_users_ecis_requestor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='overtime_checker',
            new_name='overtime_facilitator',
        ),
        migrations.AddField(
            model_name='users',
            name='overtime_importer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='overtime_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
