# Generated by Django 5.0.3 on 2025-06-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0030_rename_overtime_checker_users_overtime_facilitator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='wip_checker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='wip_counter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='wip_facilitator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='wip_user',
            field=models.BooleanField(default=False),
        ),
    ]
