# Generated by Django 5.0.3 on 2025-06-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0031_users_wip_checker_users_wip_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='job_order_spectator',
            field=models.BooleanField(default=False),
        ),
    ]
