# Generated by Django 5.0.3 on 2025-10-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0032_users_job_order_spectator'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='quality_control_user',
            field=models.BooleanField(default=False),
        ),
    ]
