# Generated by Django 5.0.3 on 2025-10-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0033_users_quality_control_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='quality_control_user',
            new_name='quality_control_engineering',
        ),
        migrations.AddField(
            model_name='users',
            name='quality_control_production',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='quality_control_qa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='quality_control_warehouse',
            field=models.BooleanField(default=False),
        ),
    ]
