# Generated by Django 5.0.3 on 2025-10-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0034_rename_quality_control_user_users_quality_control_engineering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='quality_control_user',
            field=models.BooleanField(default=False),
        ),
    ]
