# Generated by Django 5.0.3 on 2025-10-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0035_users_quality_control_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='stock_declaration_production',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='stock_declaration_purchasing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='stock_declaration_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='stock_declaration_warehouse',
            field=models.BooleanField(default=False),
        ),
    ]
