# Generated by Django 5.0.3 on 2025-10-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0036_users_stock_declaration_production_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='docunotification_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='docunotification_requestor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='docunotification_user',
            field=models.BooleanField(default=False),
        ),
    ]
