# Generated by Django 5.0.3 on 2025-10-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0037_users_docunotification_admin_and_more'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='line',
        ),
        migrations.AddField(
            model_name='users',
            name='line',
            field=models.ManyToManyField(related_name='user_line', to='settings.line'),
        ),
    ]
