# Generated by Django 5.0.3 on 2025-10-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0038_remove_users_line_users_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='job_order_pmd',
            field=models.BooleanField(default=False),
        ),
    ]
