# Generated by Django 5.0.3 on 2025-10-27 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0039_users_job_order_pmd'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='default_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_line_users', to='settings.line'),
        ),
    ]
