# Generated by Django 5.0.3 on 2025-12-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0040_users_default_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='meetingscheduler_user',
            field=models.BooleanField(default=False),
        ),
    ]
