# Generated by Django 5.0.3 on 2025-12-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0041_users_meetingscheduler_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='meetingadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='meetingscheduler',
            field=models.BooleanField(default=False),
        ),
    ]
