# Generated by Django 5.0.3 on 2025-12-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0042_users_meetingadmin_users_meetingscheduler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='overtime_allocator',
        ),
        migrations.RemoveField(
            model_name='users',
            name='overtime_importer',
        ),
        migrations.RemoveField(
            model_name='users',
            name='overtime_supervisor',
        ),
    ]
