# Generated by Django 5.0.3 on 2025-12-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0043_remove_users_overtime_allocator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='overtime_shuttle_admin',
            field=models.BooleanField(default=False),
        ),
    ]
