# Generated by Django 5.0.3 on 2026-01-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalusers', '0044_users_overtime_shuttle_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='dcf_qsd',
            field=models.BooleanField(default=False),
        ),
    ]
