version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ${DJANGO_DB_NAME:-UniSync}
      MYSQL_USER: ${DJANGO_DB_USER:-misadmin}
      MYSQL_PASSWORD: ${DJANGO_DB_PASSWORD:-FADLOCKED960052}
      TZ: ${TZ:-Asia/Manila}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: django-app
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn pdnportal.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/static/images
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/static/images
    depends_on:
      - web

volumes:
  db_data:
  static_volume:
  media_volume:
