# Generated by Django 5.0.3 on 2025-05-16 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=2, unique=True)),
                ('current_sequence', models.PositiveIntegerField(default=1)),
                ('year', models.CharField(max_length=2)),
            ],
            options={
                'unique_together': {('category', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ECIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('OR', 'Customer / Complaint Countermeasure'), ('YE', 'Yokodoshi'), ('PN', 'Manpower Related'), ('LG', 'Productivity / Tooling Improvement'), ('GR', 'Customer Request'), ('BL', 'Material Related'), ('GY', 'Machine Related')], max_length=2)),
                ('number', models.CharField(max_length=12, unique=True)),
                ('date_prepared', models.DateField(auto_now_add=True)),
                ('department', models.CharField(max_length=100)),
                ('requested_by', models.CharField(max_length=100)),
                ('customer', models.CharField(blank=True, max_length=100)),
                ('line_supervisor', models.CharField(blank=True, max_length=100)),
                ('affected_parts', models.TextField()),
                ('details_change', models.TextField()),
                ('implementation_date', models.DateField()),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('On Hold', 'On Hold'), ('For Review', 'For Review'), ('Canceled', 'Canceled')], default='Approved', max_length=20)),
                ('facilitator_remarks', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecis_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ECIS',
                'verbose_name_plural': 'ECIS',
                'ordering': ['-last_updated'],
            },
        ),
    ]
