# Generated by Django 5.0.3 on 2025-05-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecis',
            name='category',
            field=models.CharField(choices=[('OR', 'Customer / Complaint Countermeasure'), ('YE', 'Yokodoshi'), ('PN', 'Manpower Related'), ('LG', 'Productivity / Tooling Improvement'), ('GR', 'Customer Request'), ('L', 'Material Related'), ('GY', 'Machine Related')], max_length=2),
        ),
    ]
