# Generated by Django 5.0.3 on 2025-05-17 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecis', '0002_alter_ecis_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecis',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('On Hold', 'On Hold'), ('For Review', 'For Review'), ('Needs Revision', 'Needs Revision'), ('Canceled', 'Canceled')], default='Approved', max_length=20),
        ),
        migrations.CreateModel(
            name='FacilitatorRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecis_remarks', to=settings.AUTH_USER_MODEL)),
                ('ecis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='ecis.ecis')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
