# Generated by Django 5.0.3 on 2025-05-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecis', '0003_alter_ecis_status_facilitatorremark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacilitatorRemark',
        ),
    ]
