# Generated by Django 5.0.3 on 2026-01-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecis', '0004_delete_facilitatorremark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycounter',
            name='category',
            field=models.CharField(max_length=2),
        ),
    ]
