# Generated by Django 5.0.3 on 2026-01-14 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecis', '0005_alter_categorycounter_category'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecis',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.line'),
        ),
    ]
