# Generated by Django 5.1.6 on 2025-02-13 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenControlNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=100, null=True)),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='greenJoPreparer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JOLogsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jo_number', models.CharField(max_length=50, null=True)),
                ('line', models.CharField(max_length=100, null=True)),
                ('jo_type', models.CharField(max_length=100, null=True)),
                ('jo_color', models.CharField(max_length=100, null=True)),
                ('details', models.TextField()),
                ('additional_info', models.TextField()),
                ('status', models.CharField(default='Processing', max_length=50)),
                ('action_taken', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('target_date', models.DateTimeField(auto_now=True)),
                ('target_date_reason', models.TextField()),
                ('date_complete', models.DateTimeField(auto_now=True)),
                ('in_charge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='JORequestInCharge', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='JoRequestPreparer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JORouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Waiting for Approval', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('request_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joApprover', to=settings.AUTH_USER_MODEL)),
                ('jo_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joRouting', to='joborder.jologsheet')),
                ('jo_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joPreparer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrangeControlNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=100, null=True)),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orangeJoPreparer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhiteControlNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=100, null=True)),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whiteJoPreparer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YellowControlNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=100, null=True)),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yellowJoPreparer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
