# Generated by Django 5.1.6 on 2025-02-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jologsheet',
            name='jo_tools',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
