# Generated by Django 5.1.6 on 2025-02-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0002_jologsheet_jo_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='jologsheet',
            name='date_received',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
