# Generated by Django 5.0.3 on 2025-02-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0003_jologsheet_date_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jologsheet',
            name='date_complete',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='jologsheet',
            name='date_received',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='jologsheet',
            name='target_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
