# Generated by Django 5.0.3 on 2025-02-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0004_alter_jologsheet_date_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jologsheet',
            name='date_complete',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='jologsheet',
            name='date_received',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='jologsheet',
            name='target_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='jorouting',
            name='approved_at',
            field=models.DateTimeField(null=True),
        ),
    ]
