# Generated by Django 5.0.3 on 2025-02-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0005_alter_jologsheet_date_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jorouting',
            name='status',
            field=models.CharField(default='Processing', max_length=50),
        ),
    ]
