# Generated by Django 5.0.3 on 2025-02-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0006_alter_jorouting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jologsheet',
            name='action_taken',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jologsheet',
            name='additional_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jologsheet',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jologsheet',
            name='target_date_reason',
            field=models.TextField(null=True),
        ),
    ]
