# Generated by Django 5.0.3 on 2025-02-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0007_alter_jologsheet_action_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jorouting',
            name='first_approver',
            field=models.BooleanField(default=False),
        ),
    ]
