# Generated by Django 5.0.3 on 2025-04-10 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0008_jorouting_first_approver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jologsheet',
            name='line',
        ),
    ]
