# Generated by Django 5.0.3 on 2025-04-10 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0009_remove_jologsheet_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greencontrolnumber',
            name='line',
        ),
        migrations.RemoveField(
            model_name='orangecontrolnumber',
            name='line',
        ),
        migrations.RemoveField(
            model_name='whitecontrolnumber',
            name='line',
        ),
        migrations.RemoveField(
            model_name='yellowcontrolnumber',
            name='line',
        ),
    ]
