# Generated by Django 5.0.3 on 2025-04-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0010_remove_greencontrolnumber_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jologsheet',
            name='status',
            field=models.CharField(choices=[('forapproval', 'For Approval'), ('forcompletion', 'For Completion'), ('forchecking', 'For Checking'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('closed', 'Closed'), ('rejected', 'Disapproved')], default='forapproval', max_length=50),
        ),
    ]
