# Generated by Django 5.0.3 on 2025-04-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0011_alter_jologsheet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jologsheet',
            name='status',
            field=models.CharField(choices=[('Routing', 'Routing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Closed', 'Closed'), ('Rejected', 'Disapproved')], default='forapproval', max_length=50),
        ),
    ]
