# Generated by Django 5.0.3 on 2025-04-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0012_alter_jologsheet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jorouting',
            name='approver_sequence',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jologsheet',
            name='status',
            field=models.CharField(choices=[('Routing', 'Routing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Closed', 'Closed'), ('Rejected', 'Rejected')], default='Routing', max_length=50),
        ),
    ]
