# Generated by Django 5.0.3 on 2025-04-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0013_jorouting_approver_sequence_alter_jologsheet_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jologsheet',
            name='additional_info',
        ),
        migrations.AddField(
            model_name='jologsheet',
            name='requestor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jologsheet',
            name='status',
            field=models.CharField(choices=[('Routing', 'Routing'), ('Completed', 'Completed'), ('Checked', 'Checked'), ('Cancelled', 'Cancelled'), ('Closed', 'Closed'), ('Rejected', 'Rejected')], default='Routing', max_length=50),
        ),
        migrations.AlterField(
            model_name='jorouting',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
