# Generated by Django 5.0.3 on 2025-04-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0014_remove_jologsheet_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jologsheet',
            name='target_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
