# Generated by Django 5.0.3 on 2025-04-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0015_alter_jologsheet_target_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jologsheet',
            name='target_date_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
