# Generated by Django 5.0.3 on 2025-05-24 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0016_alter_jologsheet_target_date_reason'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jologsheet',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joLine', to='settings.line'),
        ),
    ]
