# Generated by Django 5.0.3 on 2025-10-15 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0017_jologsheet_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jorouting',
            name='approver_sequence',
        ),
        migrations.RemoveField(
            model_name='jorouting',
            name='first_approver',
        ),
        migrations.RemoveField(
            model_name='jorouting',
            name='jo_number',
        ),
        migrations.AlterField(
            model_name='jorouting',
            name='jo_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joRouting', to='joborder.jologsheet'),
        ),
        migrations.AlterField(
            model_name='jorouting',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved'), ('viewed', 'Viewed')], default='Pending', max_length=15),
        ),
    ]
