# Generated by Django 5.0.3 on 2025-10-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0018_remove_jorouting_approver_sequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jorouting',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved'), ('viewed', 'Viewed')], default='Pending', max_length=15),
        ),
    ]
