# Generated by Django 5.0.3 on 2025-10-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0019_alter_jorouting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jorouting',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved'), ('viewed', 'Viewed'), ('cancelled', 'Cancelled')], default='Pending', max_length=15),
        ),
    ]
