# Generated by Django 5.0.3 on 2025-10-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0020_alter_jorouting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jologsheet',
            name='date_of_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jologsheet',
            name='priority_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Low', max_length=20),
        ),
        migrations.AddField(
            model_name='jologsheet',
            name='quality_matter',
            field=models.BooleanField(default=False),
        ),
    ]
