# Generated by Django 5.0.3 on 2025-10-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0021_jologsheet_date_of_completion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jologsheet',
            name='date_of_completion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
