# Generated by Django 5.0.3 on 2025-10-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0022_alter_jologsheet_date_of_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jologsheet',
            name='status',
            field=models.CharField(choices=[('Routing', 'Routing'), ('Completed', 'Completed'), ('Checked', 'Checked'), ('Assigned', 'Assigned'), ('Cancelled', 'Cancelled'), ('Closed', 'Closed'), ('Rejected', 'Rejected')], default='Routing', max_length=50),
        ),
    ]
