# Generated by Django 5.0.3 on 2025-10-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0023_alter_jologsheet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jorouting',
            name='approver_sequence',
            field=models.IntegerField(default=1),
        ),
    ]
