# Generated by Django 5.0.3 on 2025-10-21 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0024_jorouting_approver_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jorouting',
            name='approver_sequence',
        ),
    ]
