# Generated by Django 5.0.3 on 2025-10-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborder', '0026_alter_jologsheet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jologsheet',
            name='status',
            field=models.CharField(choices=[('Routing', 'Routing'), ('Completed', 'Completed'), ('Checked', 'Checked'), ('Assigned', 'Assigned'), ('Cancelled', 'Cancelled'), ('Closed', 'Closed'), ('Rejected', 'Rejected'), ('OnHold', 'On Hold')], default='Routing', max_length=50),
        ),
    ]
