# Generated by Django 5.0.3 on 2025-03-05 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=500, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManhoursLogsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=500, null=True)),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=2)),
                ('line', models.CharField(max_length=50, null=True)),
                ('setup', models.IntegerField(default=0)),
                ('manhours', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('output', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_output', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_logsheet', to='manhours.machine')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_manhours', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
