# Generated by Django 5.0.3 on 2025-03-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manhourslogsheet',
            name='date_completed',
            field=models.DateTimeField(null=True),
        ),
    ]
