# Generated by Django 5.0.3 on 2025-03-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhours', '0002_manhourslogsheet_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manhourslogsheet',
            name='total_output',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
