# Generated by Django 5.0.3 on 2025-05-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhours', '0004_operators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operators',
            name='operator_name',
        ),
        migrations.AddField(
            model_name='operators',
            name='id_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='operators',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
