# Generated by Django 5.0.3 on 2025-03-15 05:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionSheetManpower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_mp', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Running', 'Running'), ('On Hold', 'On Hold'), ('Stopped', 'Stopped')], default='Running', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supervisors', models.ManyToManyField(related_name='supervisors', to=settings.AUTH_USER_MODEL)),
                ('user_to_monitor', models.ManyToManyField(related_name='user_to_monitor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('qty_per_box', models.IntegerField()),
                ('qty_per_hour', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_line', to='settings.line')),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_product', to='monitoring.monitoring')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionSchedulePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_planned', models.DateField()),
                ('shift', models.CharField(max_length=50, null=True)),
                ('planned_qty', models.CharField(max_length=10, null=True)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Change Load', 'Change Load'), ('Backlog', 'Backlog')], default='Planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_line', to='settings.line')),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_schedule', to='monitoring.monitoring')),
                ('product_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_schedule', to='monitoring.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_produced', models.IntegerField()),
                ('time_recorded', models.TimeField()),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='monitoring.monitoring')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_outputs', to=settings.AUTH_USER_MODEL)),
                ('schedule_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='monitoring.productionscheduleplan')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=2)),
                ('total_output', models.IntegerField(default=0)),
                ('date_prepared', models.DateField(auto_now_add=True)),
                ('date_verified', models.DateField(auto_now=True)),
                ('monitoring_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_sheets', to='monitoring.productionscheduleplan')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets_preparer', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets_verifier', to=settings.AUTH_USER_MODEL)),
                ('manpower', models.ManyToManyField(related_name='sheet_manpower', to='monitoring.productionsheetmanpower')),
            ],
        ),
        migrations.CreateModel(
            name='HourlyOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_hourly', models.TimeField(null=True)),
                ('target', models.IntegerField()),
                ('actual', models.IntegerField()),
                ('production_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_outputs', to='monitoring.productionsheet')),
            ],
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_center', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_center_line', to='settings.line')),
            ],
        ),
        migrations.AddField(
            model_name='productionsheetmanpower',
            name='work_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_center_mp', to='monitoring.workcenter'),
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efficiency_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage', max_digits=5, null=True)),
                ('quality_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage', max_digits=5, null=True)),
                ('units_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='monitoring.monitoring')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'monitoring')},
            },
        ),
    ]
