# Generated by Django 5.0.3 on 2025-03-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoring',
            name='user_to_monitor',
        ),
        migrations.AddField(
            model_name='monitoring',
            name='line_to_monitor',
            field=models.ManyToManyField(related_name='line_to_monitor', to='settings.line'),
        ),
    ]
