# Generated by Django 5.0.3 on 2025-03-18 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_remove_monitoring_user_to_monitor_and_more'),
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoring',
            name='line_to_monitor',
        ),
        migrations.RemoveField(
            model_name='monitoring',
            name='supervisors',
        ),
        migrations.CreateModel(
            name='LineToMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_lines', to='settings.line')),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_lines', to='monitoring.monitoring')),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorToMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_supervisors', to='monitoring.monitoring')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_supervisors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
