# Generated by Django 5.0.3 on 2025-03-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_remove_monitoring_line_to_monitor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionoutput',
            name='recorded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
