# Generated by Django 5.0.3 on 2025-03-21 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_productionoutput_recorded_at'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionoutput',
            name='user',
        ),
        migrations.AddField(
            model_name='productionoutput',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_line', to='settings.line'),
        ),
    ]
