# Generated by Django 5.0.3 on 2025-03-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_remove_productionoutput_user_productionoutput_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionoutput',
            name='shift',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=20),
        ),
    ]
