# Generated by Django 5.0.3 on 2025-03-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_productionoutput_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionoutput',
            name='time_recorded',
        ),
        migrations.AlterField(
            model_name='productionoutput',
            name='quantity_produced',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productionoutput',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
