# Generated by Django 5.0.3 on 2025-03-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_remove_productionoutput_time_recorded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionoutput',
            name='recorded_at',
            field=models.DateTimeField(),
        ),
    ]
