# Generated by Django 5.0.3 on 2025-03-25 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_alter_productionoutput_recorded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionscheduleplan',
            name='line',
        ),
    ]
