# Generated by Django 5.0.3 on 2025-03-26 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_alter_productionscheduleplan_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcenter',
            name='monitoring',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_workcenter', to='monitoring.monitoring'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productionscheduleplan',
            name='shift',
            field=models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], default='AM', max_length=2),
        ),
    ]
