# Generated by Django 5.0.3 on 2025-03-28 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_workcenter_monitoring_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.IntegerField(default=True)),
                ('time_recorded', models.DateTimeField(auto_now_add=True)),
                ('outputlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_output', to='monitoring.productionoutput')),
            ],
            options={
                'ordering': ['-time_recorded'],
            },
        ),
    ]
