# Generated by Django 5.0.3 on 2025-03-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_alter_productionscheduleplan_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputlog',
            name='time_recorded',
            field=models.DateTimeField(),
        ),
    ]
