# Generated by Django 5.0.3 on 2025-03-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0015_alter_outputlog_time_recorded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outputlog',
            options={'ordering': ['outputlog__line__line_name', '-time_recorded']},
        ),
        migrations.AddField(
            model_name='productionoutput',
            name='inspector',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
