# Generated by Django 5.0.3 on 2025-03-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0016_alter_outputlog_options_productionoutput_inspector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputlog',
            name='time_recorded',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productionscheduleplan',
            name='shift',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=2),
        ),
    ]
