# Generated by Django 5.0.3 on 2025-03-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0017_alter_outputlog_time_recorded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionscheduleplan',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productionscheduleplan',
            name='planned_qty',
            field=models.IntegerField(default=0),
        ),
    ]
