# Generated by Django 5.0.3 on 2025-03-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0018_productionscheduleplan_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionoutput',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
