# Generated by Django 5.0.3 on 2025-04-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0019_alter_productionoutput_recorded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionscheduleplan',
            name='shift',
            field=models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], default='AM', max_length=2),
        ),
    ]
