# Generated by Django 5.0.3 on 2025-04-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0028_alter_productionscheduleplan_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionscheduleplan',
            name='shift',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=2),
        ),
    ]
