# Generated by Django 5.0.3 on 2025-04-25 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0030_alter_monitoring_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionscheduleplan',
            options={},
        ),
    ]
