# Generated by Django 5.0.3 on 2025-04-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0031_alter_productionscheduleplan_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionoutput',
            name='recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
