# Generated by Django 5.0.3 on 2025-05-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0032_alter_productionoutput_recorded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionoutput',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
