# Generated by Django 5.0.3 on 2025-05-01 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0033_alter_productionoutput_recorded_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionsheetmanpower',
            name='line_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_line_inspector', to=settings.AUTH_USER_MODEL),
        ),
    ]
