# Generated by Django 5.0.3 on 2025-05-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0034_productionsheetmanpower_line_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputlog',
            name='status',
            field=models.CharField(choices=[('Met', 'Met'), ('Not Met', 'Not Met')], max_length=10, null=True),
        ),
    ]
