# Generated by Django 5.0.3 on 2025-05-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0035_outputlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputlog',
            name='time_recorded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
