# Generated by Django 5.0.3 on 2025-05-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0036_alter_outputlog_time_recorded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputlog',
            name='time_recorded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
