# Generated by Django 5.0.3 on 2025-05-30 02:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0037_alter_outputlog_time_recorded'),
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='linetomonitor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='supervisortomonitor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hourlyoutput',
            name='actual',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='hourlyoutput',
            name='target',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_monitoring_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='outputlog',
            name='output',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty_per_box',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty_per_hour',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='productionoutput',
            name='quantity_produced',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productionscheduleplan',
            name='planned_qty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='productionsheet',
            name='total_output',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='linetomonitor',
            unique_together={('monitoring', 'line')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('monitoring', 'product_name', 'line')},
        ),
        migrations.AlterUniqueTogether(
            name='productionscheduleplan',
            unique_together={('monitoring', 'date_planned', 'product_number', 'shift')},
        ),
        migrations.AlterUniqueTogether(
            name='supervisortomonitor',
            unique_together={('monitoring', 'supervisor')},
        ),
    ]
