# Generated by Django 5.0.3 on 2025-05-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0038_linetomonitor_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linetomonitor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='supervisortomonitor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
