# Generated by Django 5.0.3 on 2025-06-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0039_alter_linetomonitor_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputlog',
            name='operator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
