# Generated by Django 5.0.3 on 2025-11-02 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0040_outputlog_operator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productionscheduleplan',
            unique_together={('monitoring', 'date_planned', 'product_number', 'shift', 'status')},
        ),
    ]
