# Generated by Django 5.0.3 on 2025-05-19 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_id', models.CharField(max_length=20, unique=True)),
                ('filing_type', models.CharField(choices=[('SHIFTING', 'Shifting OT'), ('DAILY', 'Daily OT')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_filings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OT Filing',
                'verbose_name_plural': 'OT Filings',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('line', models.CharField(blank=True, max_length=100, null=True)),
                ('shuttle_service', models.CharField(blank=True, max_length=100, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
                ('employees', models.ManyToManyField(related_name='groups', to='overtime.employee')),
            ],
            options={
                'verbose_name': 'Employee Group',
                'verbose_name_plural': 'Employee Groups',
                'ordering': ['-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='DailyOT',
            fields=[
                ('filing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='daily_details', serialize=False, to='overtime.otfiling')),
                ('date', models.DateField()),
                ('schedule_type', models.CharField(choices=[('WEEKDAY', 'Weekday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday'), ('HOLIDAY', 'Holiday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.TextField()),
            ],
            options={
                'verbose_name': 'Daily OT',
                'verbose_name_plural': 'Daily OTs',
            },
        ),
        migrations.CreateModel(
            name='ShiftingOT',
            fields=[
                ('filing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shifting_details', serialize=False, to='overtime.otfiling')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('shift_type', models.CharField(choices=[('AM', 'AM Shift'), ('PM', 'PM Shift')], max_length=2)),
            ],
            options={
                'verbose_name': 'Shifting OT',
                'verbose_name_plural': 'Shifting OTs',
            },
        ),
        migrations.AddField(
            model_name='otfiling',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ot_filings', to='overtime.employeegroup'),
        ),
        migrations.CreateModel(
            name='LateFilingPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_type', models.CharField(choices=[('SHIFTING', 'Shifting OT Password'), ('DAILY', 'Daily OT Password'), ('WEEKEND', 'Weekend/Holiday Password'), ('HOLIDAY', 'Holiday Filing Password')], max_length=10, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_passwords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Late Filing Password',
                'verbose_name_plural': 'Late Filing Passwords',
            },
        ),
        migrations.CreateModel(
            name='SystemActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('EXPORT', 'Export'), ('PASSWORD', 'Password Change'), ('LOGIN', 'Login/Logout'), ('OTHER', 'Other')], max_length=10)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Activity',
                'verbose_name_plural': 'System Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeOTStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OT', 'OT'), ('NOT-OT', 'Not OT'), ('ABSENT', 'Absent'), ('LEAVE', 'Leave')], max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_statuses', to='overtime.employee')),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_statuses', to='overtime.otfiling')),
            ],
            options={
                'verbose_name': 'Employee OT Status',
                'verbose_name_plural': 'Employee OT Statuses',
                'unique_together': {('filing', 'employee')},
            },
        ),
    ]
