# Generated by Django 5.0.3 on 2025-12-04 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0003_shuttleuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShuttleUser',
        ),
    ]
