# Generated by Django 5.0.3 on 2025-12-04 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0004_delete_shuttleuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usershuttleassignment',
            name='destination_group',
        ),
        migrations.AddField(
            model_name='usershuttleassignment',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_assignments', to='overtime.destination'),
        ),
    ]
