# Generated by Django 5.0.3 on 2025-12-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0005_remove_usershuttleassignment_destination_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimefiling',
            name='employee_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usershuttleassignment',
            name='employee_id',
            field=models.CharField(max_length=200),
        ),
    ]
