# Generated by Django 5.0.3 on 2025-12-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0007_shuttleprovider_destinationgroup_shuttle_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershuttleassignment',
            name='with_vehicle',
            field=models.BooleanField(default=False),
        ),
    ]
