# Generated by Django 5.0.3 on 2025-05-15 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DCFNumberSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_number', models.PositiveIntegerField(default=1000)),
                ('prefix', models.CharField(default='DCF-', max_length=10)),
            ],
            options={
                'verbose_name': 'DCF Number Setting',
                'verbose_name_plural': 'DCF Number Settings',
            },
        ),
        migrations.CreateModel(
            name='DCF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcf_number', models.CharField(max_length=50, unique=True)),
                ('document_code', models.CharField(max_length=50)),
                ('document_title', models.CharField(max_length=255)),
                ('revision_number', models.CharField(max_length=20)),
                ('nature', models.CharField(choices=[('APQP', 'APQP'), ('ECC', 'ECC'), ('ECIS', 'ECIS'), ('ICC', 'ICC'), ('Others-PDN', 'Others-PDN'), ('Other-QAD', 'Other-QAD')], max_length=20)),
                ('details', models.TextField()),
                ('effectivity_date', models.DateField()),
                ('date_filed', models.DateTimeField(auto_now_add=True)),
                ('date_endorsed', models.DateTimeField(blank=True, null=True)),
                ('received_by', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('on_process', 'On Process'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='on_process', max_length=20)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('requisitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_dcfs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Change Form',
                'verbose_name_plural': 'Document Change Forms',
                'ordering': ['-date_filed'],
            },
        ),
        migrations.CreateModel(
            name='DCFApprovalTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_acted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dcf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='dcf.dcf')),
            ],
            options={
                'verbose_name': 'DCF Approval Timeline',
                'verbose_name_plural': 'DCF Approval Timelines',
                'ordering': ['date_acted'],
            },
        ),
    ]
