# Generated by Django 5.0.3 on 2025-05-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcf',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
