# Generated by Django 5.0.3 on 2026-01-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcf', '0002_dcf_prepared_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcf',
            name='nature',
            field=models.CharField(choices=[('APQP', 'APQP'), ('ECC', 'ECC'), ('ECIS', 'ECIS'), ('ICC', 'ICC'), ('Others-PDN', 'Others-PDN'), ('Other-QAD', 'Other-QAD'), ('Others', 'Others')], max_length=20),
        ),
    ]
