# Generated by Django 5.0.3 on 2026-01-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcf', '0003_alter_dcf_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcf',
            name='status',
            field=models.CharField(choices=[('on_process', 'On Process'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='on_process', max_length=20),
        ),
    ]
