# Generated by Django 5.0.3 on 2025-10-07 03:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color_code', models.CharField(default='#3366ff', help_text='Hex color code for UI', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Document Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title or name', max_length=255)),
                ('reference_number', models.CharField(help_text='Unique document reference', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the document')),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('notification_period', models.IntegerField(help_text='Number of days from creation date before notification is sent', validators=[django.core.validators.MinValueValidator(1)])),
                ('due_date', models.DateField(help_text='Calculated date when document is due (created_date + notification_period)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('due_soon', 'Due Soon'), ('expired', 'Expired'), ('renewed', 'Renewed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('last_notification_sent', models.DateTimeField(blank=True, null=True)),
                ('notification_count', models.IntegerField(default=0, help_text='Number of notifications sent')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes or comments', null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='document_notifications/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='docunotification.documentcategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewed_at', models.DateTimeField(auto_now_add=True)),
                ('new_notification_period', models.IntegerField(help_text='New notification period for renewed document', validators=[django.core.validators.MinValueValidator(1)])),
                ('new_due_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('new_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_from', to='docunotification.documentnotification')),
                ('original_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='docunotification.documentnotification')),
                ('renewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-renewed_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('system', 'System Alert'), ('sms', 'SMS')], max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent Successfully'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='docunotification.documentnotification')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification Histories',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_via_email', models.BooleanField(default=True)),
                ('notify_via_system', models.BooleanField(default=True)),
                ('is_cc', models.BooleanField(default=False, help_text='CC recipient (not primary)')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='docunotification.documentnotification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before_due', models.IntegerField(help_text='Days before due date to send reminder (0 = on due date, negative = after)', validators=[django.core.validators.MinValueValidator(0)])),
                ('message_template', models.TextField(help_text='Custom message for this reminder stage')),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_stages', to='docunotification.documentnotification')),
            ],
            options={
                'ordering': ['-days_before_due'],
            },
        ),
        migrations.AddIndex(
            model_name='documentnotification',
            index=models.Index(fields=['status', 'due_date'], name='docunotific_status_5ec522_idx'),
        ),
        migrations.AddIndex(
            model_name='documentnotification',
            index=models.Index(fields=['created_by', 'status'], name='docunotific_created_656531_idx'),
        ),
        migrations.AddIndex(
            model_name='documentnotification',
            index=models.Index(fields=['reference_number'], name='docunotific_referen_ffec90_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['document', 'sent_at'], name='docunotific_documen_25d4da_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['recipient', 'status'], name='docunotific_recipie_ce2287_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationrecipient',
            unique_together={('document', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='reminderstage',
            unique_together={('document', 'days_before_due')},
        ),
    ]
