# Generated by Django 5.0.3 on 2025-10-08 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docunotification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrecipient',
            name='cc_email',
            field=models.EmailField(blank=True, help_text='CC email address', max_length=254),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='email_address',
            field=models.EmailField(blank=True, help_text='Custom email address (optional, overrides user email)', max_length=254),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
