# Generated by Django 5.0.3 on 2025-10-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docunotification', '0002_notificationrecipient_cc_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentnotification',
            name='notification_sent_1day',
            field=models.BooleanField(default=False, help_text='1-day before notification sent'),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='notification_sent_2days',
            field=models.BooleanField(default=False, help_text='2-day before notification sent'),
        ),
        migrations.AddField(
            model_name='documentnotification',
            name='notification_sent_duedate',
            field=models.BooleanField(default=False, help_text='Due date notification sent'),
        ),
    ]
