# Generated by Django 5.0.3 on 2025-10-09 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docunotification', '0003_documentnotification_notification_sent_1day_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNotificationConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='docunotification.documentnotification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_confirmations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confirmed_at'],
                'indexes': [models.Index(fields=['document', 'user'], name='docunotific_documen_fac2f0_idx'), models.Index(fields=['user', 'confirmed_at'], name='docunotific_user_id_0702cc_idx')],
                'unique_together': {('document', 'user')},
            },
        ),
    ]
