# Generated by Django 5.0.3 on 2025-10-04 02:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Control Number')),
                ('stock_type', models.CharField(choices=[('critical', 'Critical Stock'), ('out_of_stock', 'Out Of Stock'), ('overstock', 'Overstock')], max_length=20, verbose_name='Stock Declaration Type')),
                ('product_number', models.CharField(max_length=100, verbose_name='Product Number')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('in_transit', models.TextField(blank=True, help_text='Optional information about items currently in transit', null=True, verbose_name='In Transit Details')),
                ('received_by_production', models.BooleanField(default=False, verbose_name='Received by Production')),
                ('date_received_by_production', models.DateTimeField(blank=True, null=True, verbose_name='Date Received by Production')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_declarations', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_declarations', to='settings.line', verbose_name='Production Line')),
            ],
            options={
                'verbose_name': 'Stock Declaration',
                'verbose_name_plural': 'Stock Declarations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['control_number'], name='stockdeclar_control_f04bc7_idx'), models.Index(fields=['stock_type'], name='stockdeclar_stock_t_43cb78_idx'), models.Index(fields=['line'], name='stockdeclar_line_id_fe458c_idx'), models.Index(fields=['-created_at'], name='stockdeclar_created_3fb4a2_idx')],
            },
        ),
    ]
