# Generated by Django 5.0.3 on 2025-10-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('stockdeclaration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockdeclaration',
            name='stockdeclar_line_id_fe458c_idx',
        ),
        migrations.RemoveField(
            model_name='stockdeclaration',
            name='line',
        ),
        migrations.AddField(
            model_name='stockdeclaration',
            name='lines',
            field=models.ManyToManyField(related_name='stock_declarations', to='settings.line', verbose_name='Production Lines'),
        ),
    ]
