# Generated by Django 5.0.3 on 2025-10-04 02:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('stockdeclaration', '0002_remove_stockdeclaration_stockdeclar_line_id_fe458c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdeclaration',
            name='status',
            field=models.CharField(choices=[('in_transit', 'In Transit'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled')], default='in_transit', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='stockdeclaration',
            index=models.Index(fields=['status'], name='stockdeclar_status_d098a1_idx'),
        ),
    ]
