# Generated by Django 5.0.3 on 2025-10-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdeclaration', '0003_stockdeclaration_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdeclaration',
            name='status',
            field=models.CharField(choices=[('filed', 'Filed'), ('in_transit', 'In Transit'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled')], default='filed', max_length=20, verbose_name='Status'),
        ),
    ]
