# Generated by Django 5.0.3 on 2025-10-27 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdeclaration', '0004_alter_stockdeclaration_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDeclarationView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Viewed At')),
                ('stock_declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_views', to='stockdeclaration.stockdeclaration', verbose_name='Stock Declaration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_declaration_views', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Stock Declaration View',
                'verbose_name_plural': 'Stock Declaration Views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', 'stock_declaration'], name='stockdeclar_user_id_19b225_idx'), models.Index(fields=['-viewed_at'], name='stockdeclar_viewed__3d99b8_idx')],
                'unique_together': {('user', 'stock_declaration')},
            },
        ),
    ]
