# Generated by Django 5.0.3 on 2025-05-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='attendees',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
