# Generated by Django 5.0.3 on 2025-10-01 07:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CutAway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Control Number')),
                ('date_prepared', models.DateField(default=django.utils.timezone.now, verbose_name='Date Prepared')),
                ('machine_number', models.CharField(max_length=100, verbose_name='Machine Number')),
                ('applicator_number_code', models.CharField(max_length=100, verbose_name='Applicator Number/Code')),
                ('crimped_quantity', models.PositiveIntegerField(verbose_name='Crimped Quantity')),
                ('product_number', models.CharField(max_length=100, verbose_name='Product Number')),
                ('terminal_part_number', models.CharField(max_length=100, verbose_name='Terminal Part Number')),
                ('received_date_by_qa', models.DateField(blank=True, null=True, verbose_name='Received Date By QA')),
                ('schedule_of_cut_away', models.DateField(verbose_name='Schedule Of Cut-Away')),
                ('status_of_cut_away', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status of Cut-Away')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('qa_remarks', models.TextField(blank=True, null=True, verbose_name='QA Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assy_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cut_aways', to='settings.line', verbose_name='Assembly Line')),
                ('qa_inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_cut_aways', to=settings.AUTH_USER_MODEL, verbose_name='QA Inspector')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cut_away_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
            ],
            options={
                'verbose_name': 'Cut Away',
                'verbose_name_plural': 'Cut Aways',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='qualitycont_created_338dbc_idx'), models.Index(fields=['schedule_of_cut_away'], name='qualitycont_schedul_85b101_idx'), models.Index(fields=['status_of_cut_away'], name='qualitycont_status__13bd9f_idx')],
            },
        ),
        migrations.CreateModel(
            name='LotOutInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rli_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='RLI Number')),
                ('request_date', models.DateField(default=django.utils.timezone.now, verbose_name='Request Date')),
                ('product_number', models.CharField(max_length=100, verbose_name='Product Number')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('line_affected', models.CharField(max_length=100, verbose_name='Line Affected')),
                ('reason_for_lot_out', models.TextField(verbose_name='Reason For Lot Out')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lot_out_inspections', to='settings.line', verbose_name='Line')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lot_out_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
            ],
            options={
                'verbose_name': 'Lot Out Inspection',
                'verbose_name_plural': 'Lot Out Inspections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='qualitycont_created_de969a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrialRunRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trr_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='TRR Number')),
                ('trial_date', models.DateField(verbose_name='Trial Date')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('product_number', models.CharField(max_length=100, verbose_name='Product Number')),
                ('process_name', models.CharField(max_length=255, verbose_name='Process Name')),
                ('trial_operator', models.CharField(max_length=255, verbose_name='Trial Operator')),
                ('change_from', models.TextField(verbose_name='Change From')),
                ('change_to', models.TextField(verbose_name='Change To')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trial_run_requests', to='settings.line', verbose_name='Line')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trial_run_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
            ],
            options={
                'verbose_name': 'Trial Run Request',
                'verbose_name_plural': 'Trial Run Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='qualitycont_created_919f41_idx'), models.Index(fields=['trial_date'], name='qualitycont_trial_d_c42bf4_idx')],
            },
        ),
    ]
