# Generated by Django 5.0.3 on 2025-10-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialrunrequest',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('submitted', 'Submitted')], default='submitted', max_length=20, verbose_name='Status'),
        ),
    ]
