# Generated by Django 5.0.3 on 2025-10-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrol', '0002_trialrunrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotoutinspection',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('submitted', 'Submitted')], default='submitted', max_length=20, verbose_name='Status'),
        ),
    ]
