# Generated by Django 5.0.3 on 2025-10-03 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrol', '0003_lotoutinspection_status'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotoutinspection',
            name='line',
        ),
        migrations.AlterField(
            model_name='lotoutinspection',
            name='line_affected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lot_out_inspections', to='settings.line', verbose_name='Line Affected'),
        ),
    ]
