# Generated by Django 5.0.3 on 2025-10-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrol', '0004_remove_lotoutinspection_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutaway',
            name='schedule_of_cut_away',
            field=models.DateField(blank=True, null=True, verbose_name='Schedule Of Cut-Away'),
        ),
    ]
