# Generated by Django 5.0.3 on 2025-10-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrol', '0005_alter_cutaway_schedule_of_cut_away'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutaway',
            name='leadwire_partnumber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Leadwire Partnumber/Combination'),
        ),
        migrations.AddField(
            model_name='cutaway',
            name='purpose',
            field=models.CharField(blank=True, choices=[('new_product', 'New Product'), ('reached_50000', 'Reached 50,000 pcs'), ('reached_100000', 'Reached 100,000 pcs'), ('new_applicator', 'New Applicator'), ('change_wire_crimper', 'Change Wire Crimper'), ('change_wire_anvil', 'Change Wire Anvil'), ('new_combination', 'New Combination'), ('big_burr', 'Big Burr'), ('change_supplier', 'Change Supplier')], max_length=50, null=True, verbose_name='Purpose'),
        ),
        migrations.AddField(
            model_name='cutaway',
            name='purpose_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reason for Changing Parts'),
        ),
        migrations.AddField(
            model_name='cutaway',
            name='rubber_seal_partnumber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rubber Seal Partnumber/Combination'),
        ),
    ]
