# Generated by Django 5.0.3 on 2025-06-18 00:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_responsible', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('FOR_CHECKING', 'For Checking'), ('CHECKED', 'Checked'), ('LOCKED', 'Locked')], default='FOR_CHECKING', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wip2_checked_sessions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wip2_created_sessions', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wip2_inventory_sessions', to='settings.line')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Masterlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('uom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Unit of Measure')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master List Item',
                'verbose_name_plural': 'Master List',
                'ordering': ['material_name'],
                'indexes': [models.Index(fields=['material_name'], name='wip_masterl_materia_5437a3_idx'), models.Index(fields=['is_active'], name='wip_masterl_is_acti_e8f00c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product List',
                'verbose_name_plural': 'Product Lists',
                'ordering': ['product_number'],
                'indexes': [models.Index(fields=['product_number'], name='wip_product_product_b906b8_idx'), models.Index(fields=['is_active'], name='wip_product_is_acti_b1ab00_idx')],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='wip.productlists')),
            ],
            options={
                'verbose_name_plural': 'Processes',
                'ordering': ['product__product_number', 'process_name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_type', models.CharField(choices=[('RAW', 'Raw Materials'), ('FINISHED', 'Finished Product'), ('WIP', 'WIP Product')], default='RAW', max_length=15)),
                ('count_tag', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('FOR_CHECKING', 'For Checking'), ('CHECKED', 'Checked')], default='FOR_CHECKING', max_length=15)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wip2_checked_entries', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='wip.inventorysession')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='wip.masterlist')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_entries', to='wip.process')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='wip.productlists')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WipMasterlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutting_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('uom', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wip_usage', to='wip.masterlist')),
                ('product_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wip_items', to='wip.productlists')),
            ],
            options={
                'verbose_name': 'WIP Master List Item',
                'verbose_name_plural': 'WIP Master List',
                'ordering': ['product_number__product_number', 'material_name__material_name'],
            },
        ),
        migrations.AddIndex(
            model_name='inventorysession',
            index=models.Index(fields=['line', 'status'], name='wip_invento_line_id_ded9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysession',
            index=models.Index(fields=['created_at'], name='wip_invento_created_587501_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysession',
            index=models.Index(fields=['status'], name='wip_invento_status_50fb99_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['product', 'process_name'], name='wip_process_product_850737_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['is_active'], name='wip_process_is_acti_88d95c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryentry',
            index=models.Index(fields=['session', 'inventory_type'], name='wip_invento_session_011da0_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryentry',
            index=models.Index(fields=['count_tag'], name='wip_invento_count_t_461857_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryentry',
            index=models.Index(fields=['status'], name='wip_invento_status_7d0a30_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryentry',
            index=models.Index(fields=['product', 'material'], name='wip_invento_product_0f27a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryentry',
            unique_together={('session', 'count_tag')},
        ),
        migrations.AddIndex(
            model_name='wipmasterlist',
            index=models.Index(fields=['product_number', 'material_name'], name='wip_wipmast_product_2b856d_idx'),
        ),
        migrations.AddIndex(
            model_name='wipmasterlist',
            index=models.Index(fields=['is_active'], name='wip_wipmast_is_acti_a9c867_idx'),
        ),
    ]
