# Generated by Django 5.0.3 on 2025-06-18 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryentry',
            unique_together=set(),
        ),
    ]
