# Generated by Django 5.0.3 on 2025-06-20 01:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0002_remove_count_tag_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryentry',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
