# Generated by Django 5.0.3 on 2025-06-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0003_alter_inventoryentry_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['process_name'], 'verbose_name_plural': 'Processes'},
        ),
        migrations.RemoveIndex(
            model_name='process',
            name='wip_process_product_850737_idx',
        ),
        migrations.RemoveField(
            model_name='process',
            name='product',
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['process_name'], name='wip_process_process_982495_idx'),
        ),
    ]
