# Generated by Django 5.0.3 on 2025-06-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0004_alter_process_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlists',
            name='uom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unit of Measure'),
        ),
    ]
