# Generated by Django 5.0.3 on 2025-06-24 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0005_add_uom_to_productlists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlists',
            name='uom',
        ),
    ]
